<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ship outside the US</name>
   <tag></tag>
   <elementGuidId>c4ca70e2-ec0d-46c8-801a-acfd5f77f879</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='GLUXCountryValue']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GLUXCountryValue</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>950f3d7f-4d75-4872-8a04-7f452493d2ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-dropdown-prompt</value>
      <webElementGuid>d2f6362a-a07b-4e5d-902e-3a822821f6d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GLUXCountryValue</value>
      <webElementGuid>b6c7dfde-ad3d-46a1-b9aa-6635d57569e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ship outside the US</value>
      <webElementGuid>1f3a8ea8-d0b8-46ef-9ac4-f1bca9515a32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GLUXCountryValue&quot;)</value>
      <webElementGuid>efd720ff-c5eb-41ea-bb69-73e16174b69a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='GLUXCountryValue']</value>
      <webElementGuid>8d78e55f-ca70-435c-a365-b5517c42d16f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='GLUXCountryListDropdown']/span/span/span</value>
      <webElementGuid>f4a0f4ad-4247-413b-a650-5817602198ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/span/span/span/span/span</value>
      <webElementGuid>5901fa8a-b417-4e3a-b70a-b547ce8b2bda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'GLUXCountryValue' and (text() = 'Ship outside the US' or . = 'Ship outside the US')]</value>
      <webElementGuid>334269f4-44cb-494d-bd20-306d51fb4869</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
