<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_See customer reviews</name>
   <tag></tag>
   <elementGuidId>dd95b867-d10f-4aa0-a5ad-81f93a444d02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='acrPopoverLink']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#acrPopoverLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>57ad42a9-2251-4d0c-bfe6-de486afb4dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acrPopoverLink</value>
      <webElementGuid>1944d0fd-bed2-4761-acc8-02e229146280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-size-base a-link-emphasis</value>
      <webElementGuid>ef7dc55d-15b9-421f-8b09-441e5fa40472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#customerReviews</value>
      <webElementGuid>3f8983c4-f7c3-4c0c-a656-9f67792a0ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>See customer reviews</value>
      <webElementGuid>ec0d87d6-d2f4-4157-a8cc-245cbdb390bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acrPopoverLink&quot;)</value>
      <webElementGuid>e887261b-2ebe-4bc7-b434-bddfee8cfefb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='acrPopoverLink']</value>
      <webElementGuid>058328e7-d13b-41c6-8649-ab36a295c6da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a-popover-content-4']/div/div/div/div[3]/a</value>
      <webElementGuid>99516dac-9dc2-47d2-ae58-42e5a89a0766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'See customer reviews')]</value>
      <webElementGuid>a258aba0-626a-4acf-bd19-c58be1205917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#customerReviews')])[19]</value>
      <webElementGuid>074f7db4-3acf-447f-aa9a-41a6ff1f5a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div/div/div/div[3]/a</value>
      <webElementGuid>33fd4e68-5d8e-4346-b9df-1796cb03cc2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'acrPopoverLink' and @href = '#customerReviews' and (text() = 'See customer reviews' or . = 'See customer reviews')]</value>
      <webElementGuid>4b1397a4-5bf4-43a5-8fdf-467ddc4a6a2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
